apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector:
    app: hello-k8s  ## Finds PODS with this label
  ports:
    - port: 80   ## PORT the Service Listens On
      targetPort: 3000    ## PORT on the Pod to forward to 
  type: LoadBalancer    ## Make the service accessible from outside the cluster
