apiVersion: v1
kind: Pod
metadata:
  name: hello-pod  # Name of the POD

spec:
  containers:   # List of containers in the POD
    - name: hello-container # Name of the container 
      image: hello-k8s:v1 # The container image we built
      ports:
        - containerPort: 3000 # PORT our application uses
